[package]
name = "can-voice-fsd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { version = "1.52", features = ["rt", "net", "io-util", "time", "sync", "macros"] }
