[package]
name = "can-voice-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
audiopus = "0.2"
audiopus_sys = { version = "0.1", default-features = false, features = ["static"] }
can-voice-proto = { path = "../can-voice-proto" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
